# Copyright 2025 OpenSynergy Indonesia
# Copyright 2025 PT. Simetri Sinergi Indonesia
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

{
    "name": "Employee External Assignment Agreement",
    "version": "14.0.2.8.0",
    "author": "OpenSynergy Indonesia, PT. Simetri Sinergi Indonesia",
    "website": "https://simetri-sinergi.id",
    "license": "AGPL-3",
    "depends": [
        "ssi_transaction_mixin",
        "ssi_transaction_confirm_mixin",
        "ssi_transaction_open_mixin",
        "ssi_transaction_done_mixin",
        "ssi_transaction_cancel_mixin",
        "ssi_transaction_terminate_mixin",
        "ssi_transaction_partner_mixin",
        "ssi_product_line_account_mixin",
        "ssi_hr_payroll",
        "ssi_employee_external_assignment",
        "ssi_transaction_pricelist_mixin",
        "ssi_cost_accounting",
        "ssi_product_usage_account_type",
        "base_automation",
        "base_duration",
    ],
    "data": [
        "security/ir_module_category/employee_external_assignment_agreement.xml",
        "security/ir_module_category/employee_external_assignment_agreement_batch.xml",
        "security/ir_module_category/employee_external_assignment_agreement_payment_term.xml",
        "security/res_groups/employee_external_assignment_agreement.xml",
        "security/res_groups/employee_external_assignment_agreement_batch.xml",
        "security/res_groups/employee_external_assignment_agreement_payment_term.xml",
        "security/ir_model_access/employee_external_assignment_agreement.xml",
        "security/ir_model_access/employee_external_assignment_agreement_batch.xml",
        "security/ir_model_access/employee_external_assignment_agreement_payment_term.xml",
        "security/ir_model_access/create_employee_external_agreement_term.xml",
        "security/ir_model_access/generate_agreement_from_batch.xml",
        "security/ir_rule/employee_external_assignment_agreement.xml",
        "security/ir_rule/employee_external_assignment_agreement_batch.xml",
        "security/ir_rule/employee_external_assignment_agreement_payment_term.xml",
        "ir_sequence/employee_external_assignment_agreement.xml",
        "ir_sequence/employee_external_assignment_agreement_batch.xml",
        "ir_sequence/employee_external_assignment_agreement_payment_term.xml",
        "policy_template/employee_external_assignment_agreement.xml",
        "policy_template/employee_external_assignment_agreement_batch.xml",
        "policy_template/employee_external_assignment_agreement_payment_term.xml",
        "sequence_template/employee_external_assignment_agreement.xml",
        "sequence_template/employee_external_assignment_agreement_batch.xml",
        "sequence_template/employee_external_assignment_agreement_payment_term.xml",
        "approval_template/employee_external_assignment_agreement.xml",
        "approval_template/employee_external_assignment_agreement_batch.xml",
        "approval_template/employee_external_assignment_agreement_payment_term.xml",
        "data/ir_cron.xml",
        "wizards/create_employee_external_agreement_term.xml",
        "wizards/generate_agreement_from_batch.xml",
        "views/hr_salary_rule.xml",
        "views/employee_external_assignment_type.xml",
        "views/employee_external_assignment_agreement_input_type.xml",
        "views/employee_external_assignment_agreement_input.xml",
        "views/employee_external_assignment_agreement_batch.xml",
        "views/employee_external_assignment_agreement.xml",
        "views/employee_external_assignment_agreement_payment_term.xml",
        "views/employee_external_assignment.xml",
        "views/hr_payslip.xml",
    ],
    "demo": [],
    "application": False,
    "installable": True,
    "auto_install": False,
}
