# Copyright 2026 OpenSynergy Indonesia
# Copyright 2026 PT. Simetri Sinergi Indonesia
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

from odoo import fields, models


class GenerateAgreementFromBatch(models.TransientModel):
    _name = "generate_agreement_from_batch"
    _description = "Generate Agreement from Batch"

    batch_id = fields.Many2one(
        string="Batch",
        comodel_name="employee_external_assignment_agreement_batch",
        required=True,
        default=lambda self: self._context.get("active_id"),
        help="Batch used as the template for the generated agreements.",
    )
    agreement_count = fields.Integer(
        string="Number of Agreements",
        default=1,
        required=True,
        help="Number of identical agreements to generate from the batch "
        "when no explicit line is provided below.",
    )
    line_ids = fields.One2many(
        comodel_name="generate_agreement_from_batch.line",
        inverse_name="wizard_id",
        string="Agreements",
        help="Explicit list of agreements to generate, one row per "
        "agreement. When left empty, Number of Agreements identical "
        "agreements are generated instead.",
    )
    receivable_account_id = fields.Many2one(
        comodel_name="account.account",
        string="Receivable Account",
        required=True,
        help="Receivable account applied to every agreement generated by "
        "this run. Each agreement can still change it afterward, since "
        "accounting configuration is not shared/locked by the batch.",
    )
    journal_id = fields.Many2one(
        comodel_name="account.journal",
        string="Journal",
        required=True,
        help="Journal applied to every agreement generated by this run. "
        "Each agreement can still change it afterward, since accounting "
        "configuration is not shared/locked by the batch.",
    )

    def action_generate(self):
        for record in self.sudo():
            result = record._generate()
        return result

    def _generate(self):
        self.ensure_one()
        Agreement = self.env["employee_external_assignment_agreement"]
        created = self.env["employee_external_assignment_agreement"]
        lines = self.line_ids or [None] * self.agreement_count
        for line in lines:
            created |= Agreement.create(self._prepare_agreement_vals(line))
        return self._open_generated_agreements(created)

    def _prepare_agreement_vals(self, line):
        self.ensure_one()
        batch = self.batch_id
        vals = {
            "batch_id": batch.id,
            "type_id": batch.type_id.id,
            "partner_id": batch.partner_id.id,
            "contact_partner_id": batch.contact_partner_id.id,
            "partner_location_id": batch.partner_location_id.id,
            "date": batch.date,
            "date_start": batch.date_start,
            "date_end": batch.date_end,
            "currency_id": batch.currency_id.id,
            "pricelist_id": batch.pricelist_id.id,
            "receivable_account_id": self.receivable_account_id.id,
            "journal_id": self.journal_id.id,
            "title": (line and line.title) or batch.title,
        }
        if line and line.partner_location_id:
            vals["partner_location_id"] = line.partner_location_id.id
        return vals

    def _open_generated_agreements(self, agreements):
        self.ensure_one()
        return {
            "name": "Generated Agreements",
            "type": "ir.actions.act_window",
            "res_model": "employee_external_assignment_agreement",
            "view_mode": "tree,form",
            "domain": [("id", "in", agreements.ids)],
        }


class GenerateAgreementFromBatchLine(models.TransientModel):
    _name = "generate_agreement_from_batch.line"
    _description = "Generate Agreement from Batch - Line"

    wizard_id = fields.Many2one(
        comodel_name="generate_agreement_from_batch",
        string="# Wizard",
        required=True,
        ondelete="cascade",
    )
    title = fields.Char(
        string="Title",
        help="Title for this generated agreement. Defaults to the batch's "
        "title when left empty.",
    )
    partner_location_id = fields.Many2one(
        comodel_name="res.partner",
        string="Location",
        help="Location for this generated agreement. Defaults to the "
        "batch's location when left empty.",
    )
